
CREATE VIEW [dbo].[VW_BALCALLEXPORT]
AS
	SELECT DISTINCT e.* 
	FROM dbo.[VW_CALLEXPORT] CM WITH (NOLOCK) 
		JOIN [dbo].CM_BALCALLEXPORT E WITH (NOLOCK) ON E.CALLID = CM.CALLID
GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\rsingh]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\musalunke]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\apoddar]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\pjain]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\mhuang]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\tkumar]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [corp\ravijaykumar]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [corp\pdwivedi]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\dmukherji]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\aughodake]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_BALCALLEXPORT] TO [CORP\aramugade]
    AS [dbo];

