CREATE VIEW [dbo].[VW_NARS_EMAIL_REPORT]
AS
	SELECT * FROM [dbo].[CM_NARS_EMAIL_REPORT]
GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\musalunke]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\pjain]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\mhuang]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\tkumar]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\dmukherji]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\aughodake]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[VW_NARS_EMAIL_REPORT] TO [CORP\aramugade]
    AS [dbo];

