CREATE TABLE [dbo].[CM_CALLEXPORT] (
    [AGNTID]  NVARCHAR (100) NULL,
    [CALLID]  BIGINT         NULL,
    [CALLDT]  DATE           NULL,
    [RGSID]   NVARCHAR (100) NULL,
    [RECDP]   NVARCHAR (100) NULL,
    [RGSACC]  NVARCHAR (100) NULL,
    [CONFAV]  INT            NULL,
    [DIS1]    NVARCHAR (100) NULL,
    [SKNM]    NVARCHAR (100) NULL,
    [SILT]    INT            NULL,
    [CSST]    NVARCHAR (30)  NULL,
    [CLDUR]   INT            NULL,
    [WRCNT]   INT            NULL,
    [LSIL]    INT            NULL,
    [AGSCR]   INT            NULL,
    [DIR]     NVARCHAR (50)  NULL,
    [EOM]     DATE           NULL,
    [RGSSEID] NVARCHAR (100) NULL,
    [PHNUMB]  NVARCHAR (30)  NULL,
    [AMWRCNT] INT            NULL,
    [CNWRCNT] INT            NULL,
    [PAYRCVD] INT            NULL,
    [SMPLFLG] INT            NULL,
    [CLNTID]  NVARCHAR (200) NULL,
    [CATCNT]  INT            NULL
)
WITH (DATA_COMPRESSION = PAGE);








GO
CREATE NONCLUSTERED INDEX [IX_CM_CALLEXPORT_CALLDT]
    ON [dbo].[CM_CALLEXPORT]([CALLID] ASC) WITH (DATA_COMPRESSION = PAGE);




GO
CREATE NONCLUSTERED INDEX [IX_CM_CALLEXPORT_AGNTID]
    ON [dbo].[CM_CALLEXPORT]([AGNTID] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IX_CM_CALLEXPORT_RGSSEID]
    ON [dbo].[CM_CALLEXPORT]([RGSSEID] ASC)
    INCLUDE([CALLID], [CALLDT], [RGSACC], [SMPLFLG]) WITH (DATA_COMPRESSION = PAGE);




GO
CREATE NONCLUSTERED INDEX [IX_CM_CALLEXPORT_RECDP_DIS1]
    ON [dbo].[CM_CALLEXPORT]([RECDP] ASC, [DIS1] ASC)
    INCLUDE([EOM], [AGNTID], [CALLID], [CALLDT], [RGSSEID], [DIR], [PHNUMB], [CLNTID], [SILT], [CLDUR], [RGSACC]) WITH (DATA_COMPRESSION = PAGE);

