CREATE TABLE [dbo].[CM_EVNTSAPI] (
    [EOM]      DATE           NULL,
    [CALLDT]   DATE           NULL,
    [CALLID]   BIGINT         NULL,
    [CATHIT]   NVARCHAR (255) NULL,
    [COMPNAME] NVARCHAR (255) NULL,
    [STTIME]   INT            NULL,
    [ENDTIME]  BIGINT         NULL
)
WITH (DATA_COMPRESSION = PAGE);








GO
CREATE NONCLUSTERED INDEX [IX_CM_EVNTSAPI_CALLID]
    ON [dbo].[CM_EVNTSAPI]([CALLID] ASC)
    INCLUDE([EOM], [CATHIT], [COMPNAME], [STTIME], [ENDTIME]);




GO
CREATE NONCLUSTERED INDEX [IX_CM_EVNTSAPI_CALLDT]
    ON [dbo].[CM_EVNTSAPI]([CALLDT] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IX_CM_EVNTSAPI_EOM_CATHIT_CALLDT]
    ON [dbo].[CM_EVNTSAPI]([EOM] ASC, [CATHIT] ASC, [CALLDT] ASC)
    INCLUDE([CALLID], [STTIME]);

