CREATE TABLE [dbo].[CM_SIMCXBEHA] (
    [EOM]        DATE            NULL,
    [AGNTID]     NVARCHAR (100)  NULL,
    [CALLID]     FLOAT (53)      NULL,
    [CALLDT]     DATE            NULL,
    [DIR]        NVARCHAR (50)   NULL,
    [RECDP]      NVARCHAR (15)   NULL,
    [PHNUMB]     NVARCHAR (15)   NULL,
    [CLNTID]     NVARCHAR (200)  NULL,
    [SILT]       FLOAT (53)      NULL,
    [CLDUR]      FLOAT (53)      NULL,
    [DIS1CAT]    NVARCHAR (10)   NULL,
    [DIS1]       NVARCHAR (100)  NULL,
    [RGSSEID]    NVARCHAR (4000) NULL,
    [RGSACC]     NVARCHAR (100)  NULL,
    [CALLCOUNT]  INT             NOT NULL,
    [STRNBG]     VARCHAR (14)    NOT NULL,
    [WKNUMB]     VARCHAR (6)     NOT NULL,
    [COMPNAME]   NVARCHAR (255)  NULL,
    [STTIME]     FLOAT (53)      NULL,
    [CATHITCATG] NVARCHAR (150)  NULL,
    [CATGFLG]    INT             NOT NULL
);




GO
CREATE NONCLUSTERED INDEX [IX_CM_SIMCXBEHA_CALLDT]
    ON [dbo].[CM_SIMCXBEHA]([CALLDT] ASC)
    INCLUDE([EOM], [AGNTID], [CALLID], [DIR], [RECDP], [PHNUMB], [CLNTID], [SILT], [CLDUR], [DIS1CAT], [DIS1], [RGSSEID], [RGSACC], [CALLCOUNT], [STRNBG], [WKNUMB], [COMPNAME], [STTIME], [CATHITCATG], [CATGFLG]) WITH (DATA_COMPRESSION = PAGE);


GO
CREATE NONCLUSTERED INDEX [IX_CM_SIMCXBEHA_CALLID]
    ON [dbo].[CM_SIMCXBEHA]([CALLID] ASC)
    INCLUDE([EOM], [AGNTID], [CALLDT], [DIR], [RECDP], [PHNUMB], [CLNTID], [SILT], [CLDUR], [DIS1CAT], [DIS1], [RGSSEID], [RGSACC], [CALLCOUNT], [STRNBG], [WKNUMB], [COMPNAME], [STTIME], [CATHITCATG], [CATGFLG]) WITH (DATA_COMPRESSION = PAGE);


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\musalunke]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\musalunke]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\musalunke]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\pjain]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\pjain]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\pjain]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\mhuang]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\mhuang]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\mhuang]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\tkumar]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\dmukherji]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aughodake]
    AS [dbo];


GO
GRANT UPDATE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aramugade]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\tkumar]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\dmukherji]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aughodake]
    AS [dbo];


GO
GRANT SELECT
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aramugade]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\tkumar]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\dmukherji]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aughodake]
    AS [dbo];


GO
GRANT DELETE
    ON OBJECT::[dbo].[CM_SIMCXBEHA] TO [CORP\aramugade]
    AS [dbo];

