CREATE TABLE [dbo].[MedProd_ACCT_OFFICE_20241106] (
    [ARACID]     DECIMAL (13) NOT NULL,
    [ARACCLACCT] VARCHAR (30) NULL,
    [ARACCLTID]  VARCHAR (6)  NULL,
    [ARRELOFFID] VARCHAR (15) NULL,
    [STOFFDESC]  VARCHAR (40) NULL,
    [ARRELCLDPT] VARCHAR (5)  NULL,
    [ARDPDESC]   VARCHAR (40) NULL
);

