table RPT_Active_Inv_Performance
	lineageTag: debeac8a-3fe3-432d-a6cb-b3cb92898322

	measure 'Avg Balance' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[balances]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: ad9087ab-d2a9-4f5c-9d17-ac74fba2dc89

	measure 'Call Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[calls]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 88f810cb-8e4b-482a-b6dc-01cd213dc108

	measure 'Unq Call Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_calls]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 02459bbd-5959-46f7-951c-698abd54b465

	measure 'RPC Call Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[rpc_calls]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1becbec7-f136-424d-ad2b-95ea45c16905

	measure 'Unq RPC Call Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_rpc_calls]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 081098cb-1aff-4e5d-ba53-dbb98022f02a

	measure 'Letter Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[letters]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 792e2956-e4bf-4a8f-91ce-15f818ae79a5

	measure 'Unq Letter Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_letters]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9b90b3ab-3786-4f63-a9d1-af5d9f230a33

	measure 'Account Conversion' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_payers]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 730b2f01-f187-4b0c-84c8-0b5f428a3912

	measure 'Payments per Call' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[payments]),SUM(RPT_Active_Inv_Performance[calls])))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 9b8cec1e-d000-4b53-befb-fc41b143b261

	measure Liquidation = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[payments]),SUM(RPT_Active_Inv_Performance[balances])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d870ccac-3749-44e9-a20c-32e0cf7cda5f

	measure 'Gross Unit Yield' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[payments]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 86f8bc87-9340-46a6-93f7-7e440933542e

	measure DateRange = ```
			
			VAR RangeStart = Min(RPT_Active_Inv_Performance[rpt_month]) 
			VAR RangeEnd = Max(RPT_Active_Inv_Performance[rpt_month]) 
			Return
			CONCATENATE(CONCATENATE(RangeStart," - "),RangeEnd)
			```
		isHidden
		lineageTag: 4bdd859a-f429-4128-a245-1ae131acd00c

		changedProperty = IsHidden

	measure SelectedValue = SELECTEDVALUE(RPT_Active_Inv_Performance[Month-Year])
		isHidden
		lineageTag: ef131cba-7018-4090-b961-384f8c750be0

		changedProperty = IsHidden

	measure 'Top 10 Clients' =
			
			VAR ClientsbyPayments = RANKX(ALL(RPT_Active_Inv_Performance[clientparent_new]),calculate(SUM(RPT_Active_Inv_Performance[payments])),,DESC,Dense)
			RETURN
			IF(ClientsbyPayments <= 'Select Top N Clients'[Select Top N Clients Value] , calculate(SUM(RPT_Active_Inv_Performance[payments])), BLANK())
		isHidden
		lineageTag: beacd4a7-f560-4d7f-8685-3389633b3c93

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'List DateRange' = ```
			
			VAR RangeStart = Min(RPT_Active_Inv_Performance[rpt_month]) 
			VAR RangeEnd = Max(RPT_Active_Inv_Performance[rpt_month]) 
			Return
			CONCATENATE(CONCATENATE(format(RangeStart,"MMM-YY")," - "),format(RangeEnd,"MMM-YY"))
			```
		isHidden
		lineageTag: 696a0f76-24d1-45e8-849c-eda01416ddc2

		changedProperty = IsHidden

	measure 'Call Penetration (OB)' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[calls_ob]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 88d6d737-68c4-426f-b6f2-6b05d1d3d47c

	measure 'Call Penetration (IB)' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[calls_ib]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: ad18eec4-45ee-48d2-afaa-8032037e1e67

	measure 'Unq RPC Call Penetration (IB)' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_rpc_calls_ib]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0f956e7b-4b2d-4d0c-b5e3-f5cea34ba845

	measure 'Unq RPC Call Penetration (OB)' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_rpc_calls_ob]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d1318f22-e0f0-439b-a2d8-4bf9f082ef10

	measure 'SMS Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[sms_sent]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: c3f00bb3-d1a3-4804-8e52-63d20f8ed0df

	measure 'Unq SMS Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_sms_sent]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 9d0fcb76-14f0-4bba-a40e-e8a9bd524f0b

	measure 'Email Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[emails_sent]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 377385ad-81cf-4cec-afda-a366eef728a9

	measure 'Unq Email Penetration' = CALCULATE(DIVIDE(SUM(RPT_Active_Inv_Performance[unq_emails_sent]),SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7505062e-d76d-4a41-a941-2867524ea68f

	measure 'Total Attempts Across all Channels' = CALCULATE(SUM(RPT_Active_Inv_Performance[calls])+SUM(RPT_Active_Inv_Performance[sms_sent])+SUM(RPT_Active_Inv_Performance[letters])+SUM(RPT_Active_Inv_Performance[emails_sent]))
		formatString: #,0
		lineageTag: 4c6f3d15-05ee-4cc5-bdb1-6be880bdf0ab

	measure 'Penetration Across all Channels' = CALCULATE(DIVIDE([Total Attempts Across all Channels],SUM(RPT_Active_Inv_Performance[accounts])))
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 1770d09c-f001-42a1-82ba-e90706f66323

	column rpt_month
		dataType: dateTime
		formatString: m/d/yyyy
		lineageTag: 3ce8f5ee-b26f-4c09-ad07-9a2119ab8b72
		summarizeBy: none
		sourceColumn: rpt_month

		variation Variation
			isDefault
			relationship: 71b230f2-1b33-4f02-94da-85fec6f15c26
			defaultHierarchy: LocalDateTable_d34c2181-819f-4f7d-9961-c8d938171d52.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column clientparent
		dataType: string
		isHidden
		lineageTag: ebf679d3-b52f-43cb-87f2-c9fe5bb4b2d1
		summarizeBy: none
		sourceColumn: clientparent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ClientId
		dataType: string
		lineageTag: d2b3973d-3129-47fd-9885-9b5abca3e202
		summarizeBy: none
		sourceColumn: ClientId

		annotation SummarizationSetBy = Automatic

	column list_age
		dataType: string
		lineageTag: 88313b44-09a3-409d-bbf7-61b7da075095
		summarizeBy: none
		sourceColumn: list_age

		annotation SummarizationSetBy = Automatic

	column balance_group
		dataType: string
		lineageTag: 73f080d2-8932-499e-be12-74ad99af36ff
		summarizeBy: none
		sourceColumn: balance_group

		annotation SummarizationSetBy = Automatic

	column accounts
		dataType: int64
		formatString: #,0
		lineageTag: 3b68552c-558e-4a1c-8a8f-fd0edd966ce6
		summarizeBy: sum
		sourceColumn: accounts

		annotation SummarizationSetBy = Automatic

	column balances
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 6fc078f3-f011-4e81-bdab-677e4d2246d4
		summarizeBy: sum
		sourceColumn: balances

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column calls
		dataType: int64
		formatString: #,0
		lineageTag: 2e69cf58-3567-4c3c-81e6-84b1c43ec9a5
		summarizeBy: sum
		sourceColumn: calls

		annotation SummarizationSetBy = Automatic

	column unq_calls
		dataType: int64
		formatString: 0
		lineageTag: 1cbf25c5-924a-41d1-90d7-1908b47f12f2
		summarizeBy: sum
		sourceColumn: unq_calls

		annotation SummarizationSetBy = Automatic

	column rpc_calls
		dataType: int64
		formatString: 0
		lineageTag: 98d05e1c-8451-4dc8-9abf-490162845784
		summarizeBy: sum
		sourceColumn: rpc_calls

		annotation SummarizationSetBy = Automatic

	column unq_rpc_calls
		dataType: int64
		formatString: #,0
		lineageTag: 562b52f6-65c2-4f43-b561-73c597f81d35
		summarizeBy: sum
		sourceColumn: unq_rpc_calls

		annotation SummarizationSetBy = Automatic

	column letters
		dataType: int64
		formatString: #,0
		lineageTag: 53b288aa-fc9e-4ca9-aa04-14a74e5ad3e7
		summarizeBy: sum
		sourceColumn: letters

		annotation SummarizationSetBy = Automatic

	column unq_letters
		dataType: int64
		formatString: 0
		lineageTag: aa543637-582a-4022-8ec8-0e140d74968b
		summarizeBy: sum
		sourceColumn: unq_letters

		annotation SummarizationSetBy = Automatic

	column payments
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: eeb912ed-0c09-4272-97c6-6fb860052b0a
		summarizeBy: sum
		sourceColumn: payments

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column payers
		dataType: int64
		formatString: #,0
		lineageTag: 1aeeb711-f81e-482f-b6c3-06ffc38a9f2c
		summarizeBy: sum
		sourceColumn: payers

		annotation SummarizationSetBy = Automatic

	column unq_payers
		dataType: int64
		formatString: #,0
		lineageTag: 589aa494-1be0-41d9-b5b1-a700e46cad08
		summarizeBy: sum
		sourceColumn: unq_payers

		annotation SummarizationSetBy = Automatic

	column Month-Year = FORMAT(RPT_Active_Inv_Performance[rpt_month],"MMM-YY")
		lineageTag: 3bba95c5-89b1-4910-8dab-b2c9dd724b48
		summarizeBy: none
		sortByColumn: YYYYMM

		annotation SummarizationSetBy = Automatic

	column 'Active Accounts > 10k'
		dataType: string
		lineageTag: 57ea07c3-b6aa-4176-89dc-d8db222d274e
		summarizeBy: none
		sourceColumn: Active Accounts > 10k

		annotation SummarizationSetBy = Automatic

	column ClientStreamId
		dataType: string
		lineageTag: 436ddef4-b98b-4f78-af30-9b7b1f98e25b
		summarizeBy: none
		sourceColumn: ClientStreamId

		annotation SummarizationSetBy = Automatic

	column ClientStream
		dataType: string
		lineageTag: 4b440d44-b03d-47b5-909b-ca9f04d5ad8c
		summarizeBy: none
		sourceColumn: ClientStream

		annotation SummarizationSetBy = Automatic

	column KeySourceSystem
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 40efc69c-0985-478a-8e4c-8e0296f9001e
		summarizeBy: sum
		sourceColumn: KeySourceSystem

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YYYYMM =
			
			VAR YYYY= YEAR(RPT_Active_Inv_Performance[rpt_month])
			VAR MM =  FORMAT(RPT_Active_Inv_Performance[rpt_month],"mm")
			RETURN
			YYYY & MM
		isHidden
		lineageTag: e5f0b28f-dcc9-405f-82ed-c7b2eb5cc9a1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column CustomerState
		dataType: string
		lineageTag: 848c7d60-76fe-4f14-b376-6f7c1bfb80da
		summarizeBy: none
		sourceColumn: CustomerState

		annotation SummarizationSetBy = Automatic

	column MYY = ```
			
			LEFT(RPT_Active_Inv_Performance[rpt_month_mo],1) & "-" & RIGHT(RPT_Active_Inv_Performance[rpt_year],2)
			---VAR rpt_month_mo = format(RPT_Active_Inv_Performance[rpt_month],"mmm")
			---VAR rpt_year = YEAR(RPT_Active_Inv_Performance[rpt_month])
			
			---RETURN
			---LEFT(rpt_month_mo,1) & "-" & RIGHT(rpt_year,2)
			
			
			```
		isHidden
		lineageTag: c3703c51-c48e-4f04-a8af-e77fae8ab75a
		summarizeBy: none
		sortByColumn: YYYYMM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rpt_month_mo = format(RPT_Active_Inv_Performance[rpt_month],"mmm")
		isHidden
		lineageTag: c31a73b5-041f-48be-992b-24a97013c2a2
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rpt_year = YEAR(RPT_Active_Inv_Performance[rpt_month])
		isHidden
		formatString: 0
		lineageTag: 5b687b18-c6d1-4d9f-ba39-0fcb16c172af
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rpt_month_nbr = month(RPT_Active_Inv_Performance[rpt_month])
		isHidden
		formatString: 0
		lineageTag: 578c738b-0765-4856-b9f3-603162f25306
		summarizeBy: sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column calls_ib
		dataType: int64
		formatString: #,0
		lineageTag: 55279c0d-b803-4ac5-9f3c-b7e457ea1e8e
		summarizeBy: sum
		sourceColumn: calls_ib

		annotation SummarizationSetBy = Automatic

	column unq_calls_ib
		dataType: int64
		formatString: 0
		lineageTag: b4bbbc96-a915-4bd5-b2a7-e5e12417277f
		summarizeBy: sum
		sourceColumn: unq_calls_ib

		annotation SummarizationSetBy = Automatic

	column rpc_calls_ib
		dataType: int64
		formatString: 0
		lineageTag: 83241047-f04a-44b9-bfcf-4b647fe1ae27
		summarizeBy: sum
		sourceColumn: rpc_calls_ib

		annotation SummarizationSetBy = Automatic

	column unq_rpc_calls_ib
		dataType: int64
		formatString: 0
		lineageTag: 8c648cac-960f-4b33-adb5-0cc49384b3b9
		summarizeBy: sum
		sourceColumn: unq_rpc_calls_ib

		annotation SummarizationSetBy = Automatic

	column calls_ob
		dataType: int64
		formatString: #,0
		lineageTag: ab8dca1e-a6cb-46eb-8a9c-2ccb039db9b1
		summarizeBy: sum
		sourceColumn: calls_ob

		annotation SummarizationSetBy = Automatic

	column unq_calls_ob
		dataType: int64
		formatString: 0
		lineageTag: 68afd24a-fb71-4d3e-aabc-9c6cf7ece9e9
		summarizeBy: sum
		sourceColumn: unq_calls_ob

		annotation SummarizationSetBy = Automatic

	column rpc_calls_ob
		dataType: int64
		formatString: 0
		lineageTag: c6b0b57d-9e62-48fc-a78e-5055f486bd25
		summarizeBy: sum
		sourceColumn: rpc_calls_ob

		annotation SummarizationSetBy = Automatic

	column unq_rpc_calls_ob
		dataType: int64
		formatString: 0
		lineageTag: ac043493-3f6c-4d84-b652-8d5cbe9b0a0e
		summarizeBy: sum
		sourceColumn: unq_rpc_calls_ob

		annotation SummarizationSetBy = Automatic

	column OfficeID
		dataType: string
		lineageTag: e162adb7-daa9-4a0e-9343-945036a6f2d8
		summarizeBy: none
		sourceColumn: OfficeID

		annotation SummarizationSetBy = Automatic

	column sms_sent
		dataType: int64
		formatString: #,0
		lineageTag: 42636a44-b811-4dd3-bcbf-2a189e4ed126
		summarizeBy: sum
		sourceColumn: sms_sent

		annotation SummarizationSetBy = Automatic

	column unq_sms_sent
		dataType: int64
		formatString: 0
		lineageTag: b5b62be1-0593-4fe8-bef8-ad8d320c8978
		summarizeBy: sum
		sourceColumn: unq_sms_sent

		annotation SummarizationSetBy = Automatic

	column emails_sent
		dataType: int64
		formatString: #,0
		lineageTag: 9849cab8-5c1c-43d3-9183-85cb3599542d
		summarizeBy: sum
		sourceColumn: emails_sent

		annotation SummarizationSetBy = Automatic

	column unq_emails_sent
		dataType: int64
		formatString: 0
		lineageTag: 69ff511f-4d3a-434b-a44f-68e7fa6c4f0a
		summarizeBy: sum
		sourceColumn: unq_emails_sent

		annotation SummarizationSetBy = Automatic

	column SourceSystem
		dataType: string
		lineageTag: e98d7232-db5e-43f4-81e7-672cccc57482
		summarizeBy: none
		sourceColumn: SourceSystem

		annotation SummarizationSetBy = Automatic

	column ClientParent_new
		dataType: string
		lineageTag: 88dfa97c-1aa5-4d03-9318-405e69bb3db2
		summarizeBy: none
		sourceColumn: ClientParent_new

		annotation SummarizationSetBy = Automatic

	partition RPT_Active_Inv_Performance-4c3d5a99-3e99-48dd-a5ec-5b57fd73c2cb = m
		mode: import
		source =
				let
				    Source = Sql.Database("DFW2-BISQL-001", "CLIENT_ANALYTICS"),
				    dbo_RPT_Active_Inv_Performance = Source{[Schema="dbo",Item="RPT_Active_Inv_Performance"]}[Data],
				    #"Merged Queries" = Table.NestedJoin(dbo_RPT_Active_Inv_Performance, {"clientparent", "rpt_month"}, #"RPT_Active_Inv_Performance (2)", {"clientparent", "rpt_month"}, "RPT_Active_Inv_Performance (2)", JoinKind.LeftOuter),
				    #"Expanded RPT_Active_Inv_Performance (2)" = Table.ExpandTableColumn(#"Merged Queries", "RPT_Active_Inv_Performance (2)", {"Active Accounts > 10k"}, {"Active Accounts > 10k"}),
				    #"Left Join DimSourceSystem" = Table.NestedJoin(#"Expanded RPT_Active_Inv_Performance (2)", {"KeySourceSystem"}, DimSourceSystem, {"KeySourceSystem"}, "DimSourceSystem", JoinKind.LeftOuter),
				    #"Expanded DimSourceSystem" = Table.ExpandTableColumn(#"Left Join DimSourceSystem", "DimSourceSystem", {"SourceSystem"}, {"SourceSystem"}),
				    #"Left Join ClientMapping" = Table.NestedJoin(#"Expanded DimSourceSystem", {"ClientId", "SourceSystem"}, ClientMapping, {"ClientId", "SourceSystem"}, "ClientMapping", JoinKind.LeftOuter),
				    #"Expanded ClientMapping" = Table.ExpandTableColumn(#"Left Join ClientMapping", "ClientMapping", {"ClientStreamId", "ClientStream", "ClientParent_new", "OfficeID"}, {"ClientStreamId", "ClientStream", "ClientParent_new", "OfficeID"}),
				    #"Filtered Rows" = Table.SelectRows(#"Expanded ClientMapping", each ([SourceSystem] <> "FAST" and [SourceSystem] <> "SMPROD"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

