table 'RPT_Active_Inv_Performance (2)'
	isHidden
	lineageTag: de6a2705-8173-4c1a-a60d-2640149831a1

	column clientparent
		dataType: string
		isHidden
		lineageTag: 4b97a40b-6176-491b-ba32-c624ec83d505
		summarizeBy: none
		sourceColumn: clientparent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column rpt_month
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 8e2b32f3-edd7-4b1d-98df-c38a9087b317
		summarizeBy: none
		sourceColumn: rpt_month

		variation Variation
			isDefault
			relationship: e0b6388a-de69-4afc-8655-407aa608ab65
			defaultHierarchy: LocalDateTable_9e2f3748-266c-47f2-bc01-28de5e126407.'Date Hierarchy'

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Count of Active Accounts'
		dataType: double
		isHidden
		lineageTag: de353852-c85d-4891-99e4-9455a24412de
		summarizeBy: sum
		sourceColumn: Count of Active Accounts

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Active Accounts > 10k'
		dataType: string
		isHidden
		lineageTag: 08951515-8adc-466e-bb5e-5270755a0d42
		summarizeBy: none
		sourceColumn: Active Accounts > 10k

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column YYYYMM =
			
			VAR YYYY= YEAR('RPT_Active_Inv_Performance (2)'[rpt_month])
			VAR MM =  FORMAT('RPT_Active_Inv_Performance (2)'[rpt_month],"mm")
			RETURN
			YYYY & MM
		isHidden
		lineageTag: d3f20dea-759d-4a00-a257-1d5e34c77849
		summarizeBy: none

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Month-Year = FORMAT('RPT_Active_Inv_Performance (2)'[rpt_month],"MMM-YY")
		isHidden
		lineageTag: 2d1d003f-e231-41d3-9917-36611ef6f496
		summarizeBy: none
		sortByColumn: YYYYMM

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'RPT_Active_Inv_Performance (2)-3aa83906-ea27-456c-9dbf-7f5ab923e031' = m
		mode: import
		source =
				let
				    Source = Sql.Database("DFW2-BISQL-001", "CLIENT_ANALYTICS"),
				    dbo_RPT_Active_Inv_Performance = Source{[Schema="dbo",Item="RPT_Active_Inv_Performance"]}[Data],
				    #"Grouped Rows" = Table.Group(dbo_RPT_Active_Inv_Performance, {"clientparent", "rpt_month"}, {{"Count of Active Accounts", each List.Sum([accounts]), type nullable number}}),
				    #"Added Conditional Column" = Table.AddColumn(#"Grouped Rows", "Active Accounts > 10k", each if [Count of Active Accounts] >= 10000 then "Yes" else "No")
				in
				    #"Added Conditional Column"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

