table 'Select Top N Clients'
	isHidden
	lineageTag: 37183144-cff6-4ca8-b118-a78950bc3678

	measure 'Select Top N Clients Value' = SELECTEDVALUE('Select Top N Clients'[Select Top N Clients], 10)
		isHidden
		lineageTag: d87a52ad-e7ba-464e-b07d-8eadabe78527

		changedProperty = IsHidden

	column 'Select Top N Clients'
		isHidden
		formatString: 0
		lineageTag: d88454b2-9f86-4b03-8685-6528fa3519e9
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	partition 'Select Top N Clients-b8323811-6207-434f-bd11-3171ec2b620e' = calculated
		mode: import
		source = GENERATESERIES(0, 50, 1)

	changedProperty = IsHidden

