table vw_Amex_ClientCodes_LookupTable
	lineageTag: 43342e78-6224-49e0-96ce-a3ba80c7c8cd

	column ClientCode
		dataType: string
		isHidden
		lineageTag: 9eb4776c-310e-4cb9-aaa5-1d81eb58af4f
		summarizeBy: none
		sourceColumn: ClientCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StandardParentCode
		dataType: string
		isHidden
		lineageTag: c554d907-4a73-4a1c-bc6c-5a45aa927c00
		summarizeBy: none
		sourceColumn: StandardParentCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		isHidden
		lineageTag: a408d17e-b5a3-4983-a0e9-3ce7cba82acb
		summarizeBy: none
		sourceColumn: Description

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FirstPartyFlag
		dataType: boolean
		isHidden
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6f8b426b-dff8-43e0-ae5c-c4f3a2872f1d
		summarizeBy: none
		sourceColumn: FirstPartyFlag

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column amex_segment
		dataType: string
		isHidden
		lineageTag: 67fd17fa-e7a0-4149-a253-d37b95c70d70
		summarizeBy: none
		sourceColumn: amex_segment

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Amex Segment'
		dataType: string
		lineageTag: b2ef7676-83c3-4143-8fc2-24618344f162
		summarizeBy: none
		sourceColumn: Amex Segment

		annotation SummarizationSetBy = Automatic

	column 'Amex Segment Group'
		dataType: string
		lineageTag: 3bc860a0-a0be-4058-8f39-6b80e54465e4
		summarizeBy: none
		sourceColumn: Amex Segment Group

		annotation SummarizationSetBy = Automatic

	partition vw_Amex_ClientCodes_LookupTable-e0c43176-1e44-4087-a9a7-39b0f9aaeebb = m
		mode: import
		source =
				let
				    Source = Sql.Database("dfw2-bisql-001", "client_analytics"),
				    dbo_vw_Amex_ClientCodes_LookupTable = Source{[Schema="dbo",Item="vw_Amex_ClientCodes_LookupTable"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(dbo_vw_Amex_ClientCodes_LookupTable,{{"Amex_Segment_Description", "Amex Segment"}, {"Amex_Segment_Group", "Amex Segment Group"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

